## 用列表创建

In [5]:
import pandas as pd
students = ['Lisha', 'Shelly', 'Greay', 'Leo', 'Marry']
df1 = pd.DataFrame(students)
print(df1)


df2 = pd.DataFrame([students])
print(df2)

        0
0   Lisha
1  Shelly
2   Greay
3     Leo
4   Marry
       0       1      2    3      4
0  Lisha  Shelly  Greay  Leo  Marry


## 用字典创建

In [2]:
import pandas as pd

dict = {'cbxxx_1UE':24491,
        'cbxxx_2UE':24492}

df=pd.DataFrame(dict.items(), columns=['Case', 'Build'])
df.set_index('Case', inplace=True)
print(df)
#df.set_index(0, inplace=True)

           Build
Case            
cbxxx_1UE  24491
cbxxx_2UE  24492


## 用嵌套列表创建

In [3]:
import pandas as pd

nest_list = [['cbxxx_1UE', 24491],
             ['cbxxx_2UE', 24492]]
print("nest list:")
print(nest_list)

df=pd.DataFrame(nest_list, columns=['Case', 'Build'])
print("dataframe created by nest list:")
print(df)

l = [['a', 'b', 'c', 'd'],
     [1, 2, 3, 4],
     ['i', 'j', 'k', 'l']]
df = pd.DataFrame(l)
print(df)

df2 = pd.DataFrame(l, index=['i1', 'i2', 'i3'], columns=['c1', 'c2', 'c3', 'c4'])
print(df2)

nest list:
[['cbxxx_1UE', 24491], ['cbxxx_2UE', 24492]]
dataframe created by nest list:
        Case  Build
0  cbxxx_1UE  24491
1  cbxxx_2UE  24492
   0  1  2  3
0  a  b  c  d
1  1  2  3  4
2  i  j  k  l
   c1 c2 c3 c4
i1  a  b  c  d
i2  1  2  3  4
i3  i  j  k  l


## 用二维数组创建

In [1]:
import numpy as np
import pandas as pd

a = np.random.standard_normal((9, 4)).round(6)
print(a)

df = pd.DataFrame(a)
print(df)

# 更改列标签-columns
df.columns = ['No1', 'No2', 'No3', 'No4']
print(df['No2'][3]) # 打印第2列第3行的数据
# 更改行标签-index
dates = pd.date_range('2015-1-1', periods=9, freq='M')
df.index = dates

print(df)

[[-0.041169  0.573374  1.436819 -0.957816]
 [ 0.430615 -0.717538 -0.478469 -0.264608]
 [ 1.418563 -0.303319 -1.21887  -0.331919]
 [-2.675773  0.468677 -0.942425  0.085257]
 [ 0.323261 -0.00405   0.79225  -1.451625]
 [ 1.928019 -0.563063 -0.073557  1.862708]
 [ 0.506523  0.28642  -1.594262  2.576778]
 [ 0.861383  0.678131 -0.424188  0.705654]
 [-0.424476 -0.250145  0.306292  0.158723]]
          0         1         2         3
0 -0.041169  0.573374  1.436819 -0.957816
1  0.430615 -0.717538 -0.478469 -0.264608
2  1.418563 -0.303319 -1.218870 -0.331919
3 -2.675773  0.468677 -0.942425  0.085257
4  0.323261 -0.004050  0.792250 -1.451625
5  1.928019 -0.563063 -0.073557  1.862708
6  0.506523  0.286420 -1.594262  2.576778
7  0.861383  0.678131 -0.424188  0.705654
8 -0.424476 -0.250145  0.306292  0.158723
0.468677
                 No1       No2       No3       No4
2015-01-31 -0.041169  0.573374  1.436819 -0.957816
2015-02-28  0.430615 -0.717538 -0.478469 -0.264608
2015-03-31  1.418563 -0.303319

In [15]:
import pandas as pd

header = ['A', 'B', 'C', 'D']
#df = pd.DataFrame(columns=header)
df = pd.DataFrame()
print(df)

list = [1, 2, 3, 4]
another_df = pd.DataFrame([list], columns=header)
print("another df:")
print(another_df)


new_df = pd.concat([df, another_df])
print("concat df:")
print(new_df)


Empty DataFrame
Columns: []
Index: []
another df:
   A  B  C  D
0  1  2  3  4
concat df:
   A  B  C  D
0  1  2  3  4
