# 简单数组

In [2]:
import numpy as np

np.array([1, 2, 3])
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

## 通过`dtype`参数指定类型

In [5]:
fa = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
fa[0][0]

np.float64(1.0)

## 数组复制

In [13]:
simple_arr1 = np.array([1, 2, 3])
simple_arr2 = np.array(simple_arr1)
simple_arr2[0] = 100

simple_arr1

array([1, 2, 3])

# 多维数组

## 相同初始化

`np.empty((2, 3))` 创建没有任何具体值的数组（初始化随机值）

In [22]:
np.empty([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

`numpy.zeros(shape, dtype=float, order='C')`

根据给定的规格和类型返回新的数组，并初始化为0。其中的order表示在存储多维数组的时候是按照C语言中的行优先还是Fortran语言中的列优先进行。

In [23]:
nda2 = np.zeros(3)
print(nda2)
print('元素类型：{}'.format(nda2.dtype))

[0. 0. 0.]
元素类型：float64


`np.ones([3,4])`：生成3x4元素值为1的数组

In [24]:
nda3 = np.ones(10)
print(nda3)
print('元素类型：{}'.format(nda3.dtype))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
元素类型：float64


`np.full([3,4], 9)`：给定初始化的值为9

In [25]:
np.full([3, 4], 9)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

## 范围创建

`np.arange(0, 90, 10)`：生成等间隔的数组。`arange()`和Python内置的`range()`类似，但前者返回数组，后者返回列表。


In [26]:
np.arange(0, 90, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

使用`linspace()`创建等差数列。注意该函数与`arange()`的差别：

1. `arange()`为左开右闭，`linspace()`为开始到结束的闭区间，可以通过`endpoint=False`来设置
2. `arange()`第3个参数为步长，`linspace()`第3个参数为个数

In [29]:
np.linspace(0, 90, 10)


array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

# 数组修改

## 重塑

### 一维 vs 多维

In [6]:
import numpy as np

a1 = np.arange(6)
a1

array([0, 1, 2, 3, 4, 5])

In [4]:
a1.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

### 变换行列

In [8]:
import numpy as np

a1 = np.array([['A',100], ['B',200], ['C',300]])
a1

array([['A', '100'],
       ['B', '200'],
       ['C', '300']], dtype='<U21')

In [9]:
a1.T

array([['A', 'B', 'C'],
       ['100', '200', '300']], dtype='<U21')