## `ndarray`创建

`numpy.zeros(shape, dtype=float, order='C')`

根据给定的规格和类型返回新的数组，并初始化为0。其中的order表示在存储多维数组的时候是按照C语言中的行优先还是Fortran语言中的列优先进行。

In [4]:
import numpy as np

print('方式一：常规数组创建')
arr = [3.0, 2, 8]
nda1 = np.array(arr)
print(nda1)
print('元素类型：{}'.format(nda1.dtype))

print('方式二：使用zeros/ones')
nda2 = np.zeros(3)
print(nda2)
print('元素类型：{}'.format(nda2.dtype))

nda3 = np.ones(10)
print(nda3)
print('元素类型：{}'.format(nda3.dtype))

方式一：常规数组创建
[3. 2. 8.]
元素类型：float64
方式二：使用zeros/ones
[0. 0. 0.]
元素类型：float64
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
元素类型：float64


创建时指定类型

In [7]:
np.array([[1, 2, 3],[4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.array([[1, 2, 3],[4, 5, 6]], dtype=np.float32)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

使用 `range`, `linspace`

In [11]:
import numpy as np 

print('使用range')
nda1 = np.arange(5)
print(nda1)

print('linspace')
nda2 = np.linspace(0, 90, 10)
print(nda2)

使用range
[0 1 2 3 4]
linspace
[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]
