## `ndarray`创建

In [1]:
import numpy as np

nda1 = np.zeros(10)
nda2 = np.ones(10)
print(nda1)
print(nda2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])